### PR TITLE
Added custom port selection

### PR DESCRIPTION
**Pull request by Ferdyverse**
Added a custom port selection. Usefull if you forget to start with -p. Maybe you want to include this into your script.

### CODE REVIEW

**Comment by ShutdownRepo** [comment]
Thank you for this PR! Actually, when I made the commit #3 I locally tested adding something like this. However, I didn't like the way it looked since the input line was not going away like CLI menus do. I'm working on it right now.

**Comment by ShutdownRepo** [comment]
I had something like this, the inputs stay printed.
```
$ shellerator
Custom address?
> 127.0.0.1
Custom port?
> 1337

[1] awk 'BEGIN {s = "/ine...................
```
However, I think I found a way. I'll commit but will need to test a few things on Windows

**Comment by ShutdownRepo** [comment]
Here it is #5

**Comment by Ferdyverse** [comment]
good solution!

**Pull request closed without merging**
